# The following line will download the latest Ubuntu Docker image to use as a foundation for 
# building our own Docker image.
FROM ubuntu:latest
RUN apt-get update 

# The following line will copy the apollo.txt file to the Docker container 
# using the path that is specified second.
COPY apollo13.txt /apollo13.txt